name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set IMAGE_TAG
        id: vars
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/secure-notes:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/secure-notes:${{ env.IMAGE_TAG }}
        
      - name: Also tag as 'latest' and push
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/secure-notes:${{ env.IMAGE_TAG }} ${{ secrets.DOCKERHUB_USERNAME }}/secure-notes:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/secure-notes:latest
    
      - name: Trigger Deploy on Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
